###
# ```{rubric} Full Name Override
# ```
# ---
# Override the release and chart name.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "autoscaling:\n"
# :end-before: "###\n"
# ```
autoscaling:
  enabled: false
fullnameOverride: ""

###
# ```{rubric} Image Values
# ```
# ---
# Describe the image to use for the node.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
image:
  pullPolicy: Always
  repository: edwardtheharris/monero-node
  tag: 0.0.1

###
# ```{rubric} Ingress Values
# ```
# ---
# Enable and configure ingress for the service.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
ingress:
  annotations: {}
  className: nginx
  enabled: true
  externalIPs: []
  hosts:
  - host: monero.breeze-blocks.net
    paths:
    - path: /
      pathType: Prefix
      port: 18080
  loadBalancerIP: ''
  secret:
    enabled: false
    crt: ''
    key: ''
  tls:
  - hosts:
    - monero.breeze-blocks.net
    secretName: monero-tls


###
# ```{rubric} Labels Values
# ```
# ---
# Labels to be applied to all resources
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
labels:
  node: k8s05.breeze-blocks.net
monero:
  login:
    enabled: false
    password: ''
    username: ''
nameOverride: "monero"

###
# ```{rubric} Image Values
# ```
# ---
# Describe the image to use for the node.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "persistence:\n"
# :end-before: "###\n"
# ```
persistence:
  blockchain:
    enabled: true
    mountPath: /srv/monero
    name: monero-blockchain-pvc
    size: 300Gi
  storageClass: csi-lvm-linear

###
# ```{rubric} Portal Values
# ```
# ---
# Portal configuration values.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "portal:\n"
# :end-before: "###\n"
# ```
portal:
  open:
    enabled: true

###
# ```{rubric} Security Context Values
# ```
# ---
# Security context for the deployment's pod.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "securityContext:\n"
# :end-before: "###\n"
# ```
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

###
# ```{rubric} Service Values
# ```
# ---
# Services for main and rpc ports.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "service:\n"
# :end-before: "###\n"
# ```
service:
  enabled: true
  main:
    name: main
    ports:
      main:
        port: 18080
        protocol: TCP
        targetPort: 18080
  rpc:
    enabled: true
    name: rpc
    ports:
      rpc:
        port: 18081
        protocol: TCP
        targetPort: 18081
  type: LoadBalancer

###
# ```{rubric} Service Account Values
# ```
# ---
# Enable and configure a new service account.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "serviceAccount:\n"
# ```
serviceAccount:
  annotations:
    app.kubernetes.io/name: monero
    app.kubernetes.io/instance: monero
  automount: true
  create: true
  name: monero
statefulset:
  replicas: 1
