###
# ```{rubric} Full Name Override
# ```
# ---
# Override the release and chart name.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "autoscaling:\n"
# :end-before: "###\n"
# ```
autoscaling:
  enabled: false
fullnameOverride: ""

###
# ```{rubric} Image Values
# ```
# ---
# Describe the image to use for the node.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
image:
  pullPolicy: IfNotPresent
  repository: edwardtheharris/monero-node
  tag: 0.0.1-846722

###
# ```{rubric} Ingress Values
# ```
# ---
# Enable and configure ingress for the service.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
ingress:
  annotations: {}
  enabled: true
  className: nginx
  hosts:
  - host: monero.breeze-blocks.net
    paths:
    - path: /
      pathType: Prefix
      port: 18080
  tls:
  - hosts:
    - monero.breeze-blocks.net
    secretName: monero-tls


###
# ```{rubric} Labels Values
# ```
# ---
# Labels to be applied to all resources
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
labels:
  node: k8s05.breeze-blocks.net

###
# ```{rubric} Monero Node Configuration Values
# ```
# ---
# Configure the monero node that will run on the cluster.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "monero:\n"
# :end-before: "###\n"
# ```
monero:
  enablednsblocklist: true
  noigd: true
  pruneblockchain: true
  publicnode: true
  rpcbindip: 0.0.0.0
  rpcbindport: "18089"
nameOverride: "monero"

###
# ```{rubric} Image Values
# ```
# ---
# Describe the image to use for the node.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "persistence:\n"
# :end-before: "###\n"
# ```
persistence:
  blockchain:
    enabled: true
    mountPath: /srv/monero
    name: monero-blockchain-pvc
    size: 300Gi
  storageClass: csi-lvm-linear

###
# ```{rubric} Portal Values
# ```
# ---
# Portal configuration values.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "portal:\n"
# :end-before: "###\n"
# ```
portal:
  open:
    enabled: true

###
# ```{rubric} Security Context Values
# ```
# ---
# Security context for the deployment's pod.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "securityContext:\n"
# :end-before: "###\n"
# ```
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

###
# ```{rubric} Service Values
# ```
# ---
# Services for main and rpc ports.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "service:\n"
# :end-before: "###\n"
# ```
service:
  enabled: true
  main:
    name: monero-main
    ports:
      main:
        port: 18080
        protocol: TCP
        targetPort: 18080
  rpc:
    enabled: true
    name: monero-rpc
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: TCP
        targetPort: 18089
  type: LoadBalancer

###
# ```{rubric} Service Account Values
# ```
# ---
# Enable and configure a new service account.
#
# ```{literalinclude} /values.yaml
# :language: yaml
# :start-at: "serviceAccount:\n"
# ```
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: monero

statefulset:
  replicas: 1
