---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.kubernetes.io/name: {{ include "monero.name" .}}
    volume.kubernetes.io/storage-provisioner: {{ .Values.persistence.storageClass }}
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "monero.name" . }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: csi-lvm-linear
  volumeMode: Filesystem
