{{- if .Values.ingress.secret.enabled -}}
---
apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.secret.crt }}
  tls.key: {{ .Values.ingress.secret.key }}
kind: Secret
metadata:
  name: monero-tls
  namespace: monero
  labels:
    {{- include "monero.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
{{- end }}
{{- if .Values.monero.login.enabled }}
---
apiVersion: v1
data:
  MONEROD_USERNAME: {{ .Values.monero.login.username }}
  MONEROD_PASSWORD: {{ .Values.monero.login.password }}
kind: Secret
metadata:
  name: monero-login
  namespace: monero
  labels:
    {{- include "monero.labels" . | nindent 4 }}
    app.kubernetes.io/component: login
{{- end -}}
