{{- if .Values.ingress.secret.crt -}}
---
apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.secret.crt }}
  tls.key: {{ .Values.ingress.secret.key }}
kind: Secret
metadata:
  name: monero-tls
  namespace: monero
  labels:
    {{ include "monero.labels" . | nindent 4 }}
type: kubernetes.io/tls
{{- end -}}
