{{- if .Values.serviceAccount.create -}}
apiVersion: v1
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "monero.labels" . | nindent 4 }}
{{- end }}
