apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "monero.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "monero.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.nameOverride }}
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        {{- include "monero.labels" . | nindent 8 }}
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.main.ports.main.port }}
              name: {{ .Values.service.main.name }}
          volumeMounts:
            - name: {{ .Values.persistence.blockchain.name }}
              mountPath: {{ .Values.persistence.blockchain.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.blockchain.name }}
      annotations:
        {{- include "monero.selectorLabels" . | nindent 8 }}
        volume.kubernetes.io/selected-node: k8s05.breeze-blocks.net
      labels:
        {{- include "monero.labels" . | nindent 8 }}
    spec:
      accessModes: ["ReadWriteOnce", "ReadWriteMany"]
      resources:
        requests:
          storage: {{ .Values.persistence.blockchain.size }}
      storageClassName: {{ .Values.persistence.storageClass }}
      volumeMode: Filesystem
