apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "monero.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "monero.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.statefulset.replicas }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "monero.labels" . | nindent 8 }}
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    spec:
      containers:
        - name: {{ .Release.Name }}
          {{- if .Values.monero.login.enabled }}
          envFrom:
            - secretRef:
                name: monero-login
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.main.port }}
              name: {{ .Release.Name }}
          resources:
            limits:
              cpu: "3"
              memory: 6Gi
            requests:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: {{ .Values.persistence.blockchain.name }}
              mountPath: {{ .Values.persistence.blockchain.mountPath }}
      nodeSelector:
        kubernetes.io/hostname: k8s05.breeze-blocks.net
      serviceAccountName: {{ .Release.Name }}
  volumeClaimTemplates:
  - metadata:
      name: monero
    spec:
      accessModes:
        - ReadWriteOnce
        - ReadWriteMany
      resources:
        requests:
          storage: 300Gi
      storageClassName: csi-lvm-linear
      volumeMode: Filesystem
